/* Dummy API Data */
export const resDataArr = [
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '305689',
			name: 'Dahiya Momos',
			uuid: '0424626b-9940-439c-89d5-5267e12c1183',
			city: '16',
			area: 'Ramdaspeth',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'ckbm2oxyarrtigewzsrg',
			cuisines: ['Chinese'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 24,
			minDeliveryTime: 24,
			maxDeliveryTime: 24,
			slaString: '24 MINS',
			lastMileTravel: 2.4000000953674316,
			slugs: {
				restaurant: 'dahiya-momos-dharampeth-dharampeth',
				city: 'nagpur',
			},
			cityState: '16',
			address: '280,\tLENDRA\tPARK RAMDASPETH-440010',
			locality: 'Central Bazaar Road',
			parentId: 67854,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID:
				'cid=6615218~p=1~eid=00000188-499e-90dd-6c45-2d9100b4014d',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.4 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '40% OFF',
				subHeader: 'UPTO ₹80',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '305689',
				deliveryTime: 24,
				minDeliveryTime: 24,
				maxDeliveryTime: 24,
				lastMileTravel: 2.4000000953674316,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.3',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '67332',
			name: 'Pind Punjabi',
			uuid: 'a11cc830-0b73-41e7-988d-b33ebf23bf2b',
			city: '16',
			area: 'Loha Pul',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'psh10puzrr6ddmhhiph8',
			cuisines: ['North Indian', 'Chinese'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 19,
			minDeliveryTime: 19,
			maxDeliveryTime: 19,
			slaString: '19 MINS',
			lastMileTravel: 0.10000000149011612,
			slugs: {
				restaurant: 'shree-ganesh-bhojnalay-sitabuldi-sitabuldi',
				city: 'nagpur',
			},
			cityState: '16',
			address:
				'Shree Ganesh Bhojnalay, Manas Chowk, Sahu Colony, Sitabuldi, Nagpur, Maharashtra',
			locality: 'Sahu Colony',
			parentId: 12427,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: 'Closes soon',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '0.1 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: '',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '67332',
				deliveryTime: 19,
				minDeliveryTime: 19,
				maxDeliveryTime: 19,
				lastMileTravel: 0.10000000149011612,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.3',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '697183',
			name: 'Burger King',
			uuid: 'f1903ba0-851a-4e12-ac78-d3f220fe9664',
			city: '16',
			area: 'Eternity Mall',
			totalRatingsString: '100+ ratings',
			cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
			cuisines: ['Burgers', 'American'],
			tags: [],
			costForTwo: 35000,
			costForTwoString: '₹350 FOR TWO',
			deliveryTime: 25,
			minDeliveryTime: 25,
			maxDeliveryTime: 25,
			slaString: '25 MINS',
			lastMileTravel: 1.2000000476837158,
			slugs: {
				restaurant: 'burger-king-nagpur-dharampeth',
				city: 'nagpur',
			},
			cityState: '16',
			address:
				'Shop No.G7,G8,F7 &F8, Ground and First Floor, Eternity Mall,Asian Highway 46, Sitabuldi,Nagpur-440010',
			locality: 'Nagpur',
			parentId: 166,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.2 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '40% OFF',
				subHeader: 'UPTO ₹80',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '697183',
				deliveryTime: 25,
				minDeliveryTime: 25,
				maxDeliveryTime: 25,
				lastMileTravel: 1.2000000476837158,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.0',
			totalRatings: 100,
			new: true,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '241417',
			name: 'Shahi Haandi Kebab & Biryani',
			uuid: '939f2acc-86af-4f0a-a5c1-29b8d85c56f6',
			city: '16',
			area: 'Gokulpeth',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'dkuk7bqc54hay72wcrhw',
			cuisines: [
				'North Indian',
				'Biryani',
				'Mughlai',
				'Indian',
				'Maharashtrian',
				'Chinese',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 23,
			minDeliveryTime: 23,
			maxDeliveryTime: 23,
			slaString: '23 MINS',
			lastMileTravel: 3.5,
			slugs: {
				restaurant: 'shahi-handi-dharampeth-dharampeth',
				city: 'nagpur',
			},
			cityState: '16',
			address:
				'Plot No 55, Flat No 102  Satyam Apartment Canal Road Gokulpeth Nagpur, Nagpur Urban, Nagpur-1 (Maharashtra)',
			locality: 'Canal Road',
			parentId: 18588,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 3300,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 3300,
				message: '',
				title: 'Delivery Charge',
				amount: '3300',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID:
				'cid=6615162~p=4~eid=00000188-499e-90dd-6c45-2d9200b4045b',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.5 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '₹125 OFF',
				subHeader: 'ABOVE ₹249',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '241417',
				deliveryTime: 23,
				minDeliveryTime: 23,
				maxDeliveryTime: 23,
				lastMileTravel: 3.5,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.2',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '190407',
			name: 'Gulshan Plaza',
			uuid: '5a2b2c09-3b0d-4e04-9919-5c9e9c2004b0',
			city: '16',
			area: 'Sitabuldi',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'gqx5ek1szotaqocasm8b',
			cuisines: [
				'North Indian',
				'Mughlai',
				'Maharashtrian',
				'Biryani',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 19,
			minDeliveryTime: 19,
			maxDeliveryTime: 19,
			slaString: '19 MINS',
			lastMileTravel: 1,
			slugs: {
				restaurant: 'gulshan-plaza-sitabuldi-sitabuldi',
				city: 'nagpur',
			},
			cityState: '16',
			address: 'in front of zero miles metro station near sitabuldi',
			locality: 'Tekdi Road',
			parentId: 91470,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '15% OFF',
				subHeader: 'ABOVE ₹800',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '190407',
				deliveryTime: 19,
				minDeliveryTime: 19,
				maxDeliveryTime: 19,
				lastMileTravel: 1,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.5',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '87718',
			name: 'Foody Moody Thali',
			uuid: '61944a9e-68b4-4287-a78c-8bb9fcca8341',
			city: '16',
			area: 'Sitabuldi',
			totalRatingsString: '10000+ ratings',
			cloudinaryImageId: 'sm2d7bzlpx6mb7qauodz',
			cuisines: [
				'Indian',
				'Thalis',
				'Chinese',
				'Biryani',
				'North Indian',
				'Punjabi',
				'Desserts',
			],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 17,
			minDeliveryTime: 17,
			maxDeliveryTime: 17,
			slaString: '17 MINS',
			lastMileTravel: 0.10000000149011612,
			slugs: {
				restaurant: 'foody-moody-dharampeth-sadar',
				city: 'nagpur',
			},
			cityState: '16',
			address:
				'Shree Ganesh Bhojnalay, Manas Chowk, Sahu Colony, Sitabuldi, Nagpur, Maharashtra',
			locality: 'Sahu Colony',
			parentId: 83005,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: 'Closes soon',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '0.1 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: 'ABOVE ₹149',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '87718',
				deliveryTime: 17,
				minDeliveryTime: 17,
				maxDeliveryTime: 17,
				lastMileTravel: 0.10000000149011612,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.6',
			totalRatings: 10000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '53868',
			name: 'KFC',
			uuid: '508c22a3-7c3e-46ed-a219-2046f04f8dd2',
			city: '16',
			area: 'Sitabuldi',
			totalRatingsString: '5000+ ratings',
			cloudinaryImageId: '56c9ab92bd79745fd152a30fa2525426',
			cuisines: [
				'Burgers',
				'Biryani',
				'American',
				'Snacks',
				'Fast Food',
			],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 23,
			minDeliveryTime: 23,
			maxDeliveryTime: 23,
			slaString: '23 MINS',
			lastMileTravel: 1,
			slugs: {
				restaurant:
					'kfc-ground-floor-eternity-mall-variety-square-bajaj-nagar',
				city: 'nagpur',
			},
			cityState: '16',
			address:
				'G1, G2, Ground Floor, Eternity Mall, Variety Square, Sitaburdi, Nagpur, Maharashtra 440010',
			locality: 'Eternity Mall',
			parentId: 547,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '20% OFF',
				subHeader: 'UPTO ₹50',
				discountTag: '',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '53868',
				deliveryTime: 23,
				minDeliveryTime: 23,
				maxDeliveryTime: 23,
				lastMileTravel: 1,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.9',
			totalRatings: 5000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '466290',
			name: 'Chacha Rolls',
			uuid: 'b3a5f713-093a-42ef-893a-c2aa39c7981c',
			city: '16',
			area: 'Mominpura',
			totalRatingsString: '500+ ratings',
			cloudinaryImageId: 'tzeuqqtxoha5c1jmaldq',
			cuisines: ['Snacks', 'Chinese', 'Fast Food'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 29,
			minDeliveryTime: 29,
			maxDeliveryTime: 29,
			slaString: '29 MINS',
			lastMileTravel: 3,
			slugs: {
				restaurant: 'chacha-rolls-nandanvan-nandanvan',
				city: 'nagpur',
			},
			cityState: '16',
			address:
				'Shop No. 3 First Floor Shohda Complex Mohammad Ali Rd Mominpura Nagpur, Maharashtra 440018, India',
			locality: 'Mohammad Ali Road',
			parentId: 280031,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 3300,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 3300,
				message: '',
				title: 'Delivery Charge',
				amount: '3300',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID:
				'cid=6796743~p=10~eid=00000188-499e-90dd-6c45-2d9400b40a06',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '₹125 OFF',
				subHeader: 'ABOVE ₹249',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '466290',
				deliveryTime: 29,
				minDeliveryTime: 29,
				maxDeliveryTime: 29,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '3.6',
			totalRatings: 500,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '72268',
			name: 'Sindh Punjab Tadka',
			uuid: '3b8f28cc-c32a-470a-beac-411d7ec254f6',
			city: '16',
			area: 'Ramdaspeth',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'kyqleymqfliyjq5izwma',
			cuisines: [
				'North Indian',
				'Mughlai',
				'Indian',
				'Punjabi',
				'Biryani',
				'Chinese',
				'Desserts',
			],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 23,
			minDeliveryTime: 23,
			maxDeliveryTime: 23,
			slaString: '23 MINS',
			lastMileTravel: 2,
			slugs: {
				restaurant: 'sindh-punjab-tadka-ramdaspeth-bajaj-nagar',
				city: 'nagpur',
			},
			cityState: '16',
			address: 'Opposite Hotel Center Point, Ramdaspeth, Nagpur',
			locality: 'Central Bazaar Road',
			parentId: 262333,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: '',
				discountTag: 'FLAT DEAL',
				headerTypeV2: 0,
			},
			sla: {
				restaurantId: '72268',
				deliveryTime: 23,
				minDeliveryTime: 23,
				maxDeliveryTime: 23,
				lastMileTravel: 2,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.5',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '81068',
			name: 'Jay Ambika Bhojnalay',
			uuid: 'c49cbef6-3dd5-4099-af14-a9efee664770',
			city: '16',
			area: 'Gandhibagh',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'lxjirbaj1iecdncb0hxm',
			cuisines: ['North Indian', 'Indian'],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 16,
			minDeliveryTime: 16,
			maxDeliveryTime: 16,
			slaString: '16 MINS',
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: 'jay-ambika-bhojnalay-gandhibagh-gandhibagh',
				city: 'nagpur',
			},
			cityState: '16',
			address: 'Shop no13 opp. Rahul hotel Ganeshpeth bus stand',
			locality: 'St Stand Road',
			parentId: 109968,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: 'distance',
						fee: 2600,
						message: '',
					},
					{
						name: 'time',
						fee: 0,
						message: '',
					},
					{
						name: 'special',
						fee: 0,
						message: '',
					},
				],
				totalFees: 2600,
				message: '',
				title: 'Delivery Charge',
				amount: '2600',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.6 kms',
			hasSurge: false,
			sla: {
				restaurantId: '81068',
				deliveryTime: 16,
				minDeliveryTime: 16,
				maxDeliveryTime: 16,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
];
